version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fx_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  updater:
    build: ./update_service
    container_name: fx_updater
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      FX_CURRENCIES: ${FX_CURRENCIES}
      FX_START_DATE: ${FX_START_DATE}
    command: ["sh", "-c", "while true; do python main.py; sleep 86400; done"]

volumes:
  pgdata:
